#!/usr/bin/env pwsh
<#
.SYNOPSIS
    Validates Pact consumer contracts against the NIOP provider's OpenAPI (Swagger) spec.
    Implemented entirely in C# — no Node.js or npm required.

.DESCRIPTION
    This script is a thin wrapper around the xUnit test
    SwaggerMockValidatorTests.PactContracts_AreCompatibleWithSwaggerSpec.

    That test:
      1. Starts an in-process WebApplicationFactory to fetch swagger.json.
      2. Locates all Pact JSON files generated by the consumer tests.
      3. Validates each interaction against the spec using Microsoft.OpenApi
         (pure C# — no Node.js / npx / swagger-mock-validator npm package).
      4. Reports pass/fail per interaction and fails the build on any mismatch.

.PARAMETER Filter
    xUnit display-name filter passed to dotnet test. Defaults to matching the
    swagger validation test. Override to run a subset.

.EXAMPLE
    # Run the Swagger mock validation (default)
    .\validate-swagger-pacts.ps1

    # Also run all other contract tests in the same pass
    .\validate-swagger-pacts.ps1 -Filter ""

.NOTES
    Prerequisites:
      - .NET SDK 10+           (dotnet --version)
      - Consumer pact files    (cd ..\NIOP_PARTNUMBERENDPOINTS_CONSUMER && dotnet test)
#>

[CmdletBinding()]
param (
    [string]$Filter = "DisplayName~OpenAPI/Swagger"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function Write-Step { param($msg) Write-Host "`n==> $msg" -ForegroundColor Cyan  }
function Write-Info  { param($msg) Write-Host "  $msg"     -ForegroundColor Gray  }
function Write-Pass  { param($msg) Write-Host "  [PASS] $msg" -ForegroundColor Green }
function Write-Fail  { param($msg) Write-Host "  [FAIL] $msg" -ForegroundColor Red   }

#  Prerequisite check: .NET SDK 
Write-Step "Checking prerequisites..."

if (-not (Get-Command dotnet -ErrorAction SilentlyContinue)) {
    Write-Error ".NET SDK not found. Install from https://dotnet.microsoft.com/download"
    exit 1
}
Write-Info ".NET SDK: $(dotnet --version)"

#  Locate the test project 
$ScriptDir   = $PSScriptRoot
$TestProject = Join-Path $ScriptDir `
    "src\Provider\NIOP.Provider.ContractTests\NIOP.Provider.ContractTests.csproj"

if (-not (Test-Path $TestProject)) {
    Write-Error "Test project not found: $TestProject"
    exit 1
}

Write-Info "Test project: $TestProject"

#  Build the test project 
Write-Step "Building contract test project..."
dotnet build $TestProject -c Release --nologo -v quiet
if ($LASTEXITCODE -ne 0) {
    Write-Fail "Build failed."
    exit 1
}
Write-Pass "Build succeeded."

#  Run the Swagger mock validator test 
Write-Step "Running Swagger mock validator test (pure C#)..."
Write-Info "Filter: '$Filter'"
Write-Info ""

$testArgs = @("test", $TestProject, "-c", "Release", "--no-build", "--nologo")
if (-not [string]::IsNullOrEmpty($Filter)) {
    $testArgs += @("--filter", $Filter)
}

dotnet @testArgs
$exitCode = $LASTEXITCODE

Write-Host ""
if ($exitCode -eq 0) {
    Write-Pass "All Pact interactions are compatible with the OpenAPI specification."
}
else {
    Write-Fail "One or more Pact interactions conflict with the OpenAPI specification."
    Write-Info "See the test output above for details."
    Write-Info ""
    Write-Info "Common fixes:"
    Write-Info "  - Update the Pact consumer test to use the correct property name/type."
    Write-Info "  - Add the missing status code to the controller's [ProducesResponseType] attributes."
    Write-Info "  - Regenerate swagger.json after fixing the API and re-run this script."
}

exit $exitCode
